discovery.server.address: https://localhost:8761/eureka/ 
server:
  port: 8081
  host: localhost
  contextPath: /myprojectservice
spring: 
  datasource: 
    platform: mysql
    dataSourceClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf-8&autoReconnect=true"
    username: bomcbp
    password: bomcbp

# mongodb配置
#spring.data.mongodb.uri: mongodb://localhost:27017/test 

# redis单机配置
#spring.redis.database: 0
#spring.redis.host: 127.0.0.1
#spring.redis.port: 6379
#spring.redis.password: 
#spring.redis.timeout: 2000

# redis集群配置
#spring.redis.cluster.enabled: true
#spring.redis.cluster.nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
#spring.redis.cluster.timeout: 30
#spring.redis.cluster.max-redirects: 12
#spring.redis.password: 

# redis 哨兵配置
#spring.redis.database: 0
#spring.redis.sentinel.master: mymaster
#spring.redis.sentinel.nodes: 127.0.0.1:6387,127.0.0.1:6388
#spring.redis.password: 

# zookeeper
#spring.zookeeper.adderss: 127.0.0.1:2181

iplatform.scheduled.lock.enabled: true
iplatform.scheduled.lock.type: jdbc
#iplatform.scheduled.lock.type=redis
#iplatform.scheduled.lock.type=mongo
#iplatform.scheduled.lock.type=zookeeper
# 不连接注册中心
eureka.client.enabled: false