discovery.server.address: https://localhost:8761/eureka/ 
server:
  port: 8081
  host: localhost
  contextPath: /myprojectservice

spring:
  data:
    neo4j:
      username: neo4j
      password: 123
      uri: bolt://127.0.0.1

# 不连接注册中心
eureka.client.enabled: false