discovery.server.address: http://localhost:8761/eureka/
# 不连接注册中心
# eureka.client.enabled: false
server:
  port: 8081
  host: localhost
  contextPath: /exampleservice
# 数据库类型(必填)
spring: 
  datasource: 
    platform: mysql
    dataSourceClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf-8&autoReconnect=true"
    username: bomcbp
    password: bomcbp