discovery.server.address: http://10.22.1.234:8761/eureka/
server:
  port: 8082
  host: localhost
  contextPath: /myprojectservice

spring:
  cloud:
    config:
      enabled: true
      profile: test

#  --discovery.server.address=http://10.22.1.234:8761/eureka/
#  --spring.cloud.config.enabled=true
#  --spring.cloud.config.profile=test
#  --spring.cloud.config.initialize=true