discovery.server.address: http://localhost:8761/eureka/ 
server:
  port: 8080
  host: localhost
  contextPath: /shardingservice
spring: 
  datasource: 
    platform: mysql
    dataSourceClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds
    username: bomcbp
    password: bomcbp
  dynamicdatasource: 
    enable: true
    names: ds_master_0,ds_slave_0,ds_master_1,ds_slave_1
    ds_master_0: 
      dataSourceClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds_master_0
      username: bomcbp
      password: bomcbp
    ds_slave_0: 
      dataSourceClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds_slave_0
      username: bomcbp
      password: bomcbp
    ds_master_1: 
      dataSourceClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds_master_1
      username: bomcbp
      password: bomcbp
    ds_slave_1: 
      dataSourceClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds_slave_1
      username: bomcbp
      password: bomcbp
# 不连接注册中心
eureka.client.enabled: false
flyway.enabled: true
sharding.jdbc.enable: true